
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountWebServiceService", targetNamespace = "http://WebServices/", wsdlLocation = "http://localhost:8686/AccountWebService?wsdl")
public class AccountWebServiceService
    extends Service
{

    private final static URL ACCOUNTWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTWEBSERVICESERVICE_EXCEPTION;
    private final static QName ACCOUNTWEBSERVICESERVICE_QNAME = new QName("http://WebServices/", "AccountWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/AccountWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTWEBSERVICESERVICE_WSDL_LOCATION = url;
        ACCOUNTWEBSERVICESERVICE_EXCEPTION = e;
    }

    public AccountWebServiceService() {
        super(__getWsdlLocation(), ACCOUNTWEBSERVICESERVICE_QNAME);
    }

    public AccountWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTWEBSERVICESERVICE_QNAME, features);
    }

    public AccountWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTWEBSERVICESERVICE_QNAME);
    }

    public AccountWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTWEBSERVICESERVICE_QNAME, features);
    }

    public AccountWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountWebService
     */
    @WebEndpoint(name = "AccountWebServicePort")
    public AccountWebService getAccountWebServicePort() {
        return super.getPort(new QName("http://WebServices/", "AccountWebServicePort"), AccountWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountWebService
     */
    @WebEndpoint(name = "AccountWebServicePort")
    public AccountWebService getAccountWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "AccountWebServicePort"), AccountWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTWEBSERVICESERVICE_EXCEPTION!= null) {
            throw ACCOUNTWEBSERVICESERVICE_EXCEPTION;
        }
        return ACCOUNTWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
